/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.vinicius;

/**
 *
 * @author SATC
 */
public class Apresentacao extends javax.swing.JFrame {

    /**
     * Creates new form Apresentacao
     */
    public Apresentacao() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPnlMusica = new javax.swing.JPanel();
        jLblMusica = new javax.swing.JLabel();
        jLblArtista = new javax.swing.JLabel();
        jLblGenero = new javax.swing.JLabel();
        jLblTempo = new javax.swing.JLabel();
        jLblNomeMusica = new javax.swing.JLabel();
        jTFArtista = new javax.swing.JTextField();
        jTFNomeMusica = new javax.swing.JTextField();
        jTFGenero = new javax.swing.JTextField();
        jTFTempo = new javax.swing.JTextField();
        jPnlApresentacao = new javax.swing.JPanel();
        jLblApresentacao = new javax.swing.JLabel();
        jLblAltoral = new javax.swing.JLabel();
        jLblCandidato = new javax.swing.JLabel();
        jLblAdaptado1 = new javax.swing.JLabel();
        jRBAltoralSim = new javax.swing.JRadioButton();
        jRBAltoralNao = new javax.swing.JRadioButton();
        jRBAdaptadaSim = new javax.swing.JRadioButton();
        jRBAdaptadaNao = new javax.swing.JRadioButton();
        jTFCodigoCandidato = new javax.swing.JTextField();
        jLblApresentacoes = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPnlMusica.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 51, 51)));

        jLblMusica.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLblMusica.setText("musica");

        jLblArtista.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLblArtista.setText("Artista :");

        jLblGenero.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLblGenero.setText("Genero :");

        jLblTempo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLblTempo.setText("Tempo :");

        jLblNomeMusica.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLblNomeMusica.setText("Nome da Musica :");

        javax.swing.GroupLayout jPnlMusicaLayout = new javax.swing.GroupLayout(jPnlMusica);
        jPnlMusica.setLayout(jPnlMusicaLayout);
        jPnlMusicaLayout.setHorizontalGroup(
            jPnlMusicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlMusicaLayout.createSequentialGroup()
                .addGroup(jPnlMusicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPnlMusicaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLblArtista))
                    .addGroup(jPnlMusicaLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jLblMusica))
                    .addGroup(jPnlMusicaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPnlMusicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLblNomeMusica)
                            .addComponent(jLblGenero)
                            .addComponent(jLblTempo)))
                    .addGroup(jPnlMusicaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTFArtista, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPnlMusicaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTFNomeMusica, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPnlMusicaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTFGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPnlMusicaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTFTempo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jPnlMusicaLayout.setVerticalGroup(
            jPnlMusicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlMusicaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLblMusica)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLblArtista)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTFArtista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLblNomeMusica)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTFNomeMusica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLblGenero)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTFGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLblTempo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTFTempo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jPnlApresentacao.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 51, 51)));

        jLblApresentacao.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLblApresentacao.setText("Apresentação");

        jLblAltoral.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLblAltoral.setText("Altoral :");

        jLblCandidato.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLblCandidato.setText("Codigo do Candidato :");

        jLblAdaptado1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLblAdaptado1.setText("Adaptado :");

        jRBAltoralSim.setText("Sim");

        jRBAltoralNao.setText("Não");

        jRBAdaptadaSim.setText("Sim");

        jRBAdaptadaNao.setText("Não");

        javax.swing.GroupLayout jPnlApresentacaoLayout = new javax.swing.GroupLayout(jPnlApresentacao);
        jPnlApresentacao.setLayout(jPnlApresentacaoLayout);
        jPnlApresentacaoLayout.setHorizontalGroup(
            jPnlApresentacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPnlApresentacaoLayout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addComponent(jLblApresentacao)
                .addGap(32, 32, 32))
            .addGroup(jPnlApresentacaoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPnlApresentacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPnlApresentacaoLayout.createSequentialGroup()
                        .addComponent(jRBAdaptadaSim)
                        .addGap(18, 18, 18)
                        .addComponent(jRBAdaptadaNao))
                    .addGroup(jPnlApresentacaoLayout.createSequentialGroup()
                        .addComponent(jRBAltoralSim)
                        .addGap(18, 18, 18)
                        .addComponent(jRBAltoralNao))
                    .addComponent(jLblAltoral)
                    .addComponent(jLblCandidato)
                    .addComponent(jLblAdaptado1)
                    .addComponent(jTFCodigoCandidato, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPnlApresentacaoLayout.setVerticalGroup(
            jPnlApresentacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlApresentacaoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLblApresentacao)
                .addGap(18, 18, 18)
                .addComponent(jLblAltoral)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPnlApresentacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRBAltoralSim)
                    .addComponent(jRBAltoralNao))
                .addGap(18, 18, 18)
                .addComponent(jLblAdaptado1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPnlApresentacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRBAdaptadaSim)
                    .addComponent(jRBAdaptadaNao))
                .addGap(13, 13, 13)
                .addComponent(jLblCandidato)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTFCodigoCandidato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLblApresentacoes.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLblApresentacoes.setText("Apresentações");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jPnlMusica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 107, Short.MAX_VALUE)
                .addComponent(jPnlApresentacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
            .addGroup(layout.createSequentialGroup()
                .addGap(189, 189, 189)
                .addComponent(jLblApresentacoes)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLblApresentacoes)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPnlApresentacao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPnlMusica, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Apresentacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Apresentacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Apresentacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Apresentacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Apresentacao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLblAdaptado1;
    private javax.swing.JLabel jLblAltoral;
    private javax.swing.JLabel jLblApresentacao;
    private javax.swing.JLabel jLblApresentacoes;
    private javax.swing.JLabel jLblArtista;
    private javax.swing.JLabel jLblCandidato;
    private javax.swing.JLabel jLblGenero;
    private javax.swing.JLabel jLblMusica;
    private javax.swing.JLabel jLblNomeMusica;
    private javax.swing.JLabel jLblTempo;
    private javax.swing.JPanel jPnlApresentacao;
    private javax.swing.JPanel jPnlMusica;
    private javax.swing.JRadioButton jRBAdaptadaNao;
    private javax.swing.JRadioButton jRBAdaptadaSim;
    private javax.swing.JRadioButton jRBAltoralNao;
    private javax.swing.JRadioButton jRBAltoralSim;
    private javax.swing.JTextField jTFArtista;
    private javax.swing.JTextField jTFCodigoCandidato;
    private javax.swing.JTextField jTFGenero;
    private javax.swing.JTextField jTFNomeMusica;
    private javax.swing.JTextField jTFTempo;
    // End of variables declaration//GEN-END:variables
}
