/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.vinicius;

import Singleton.SAvaliacao;
import Singleton.SCandidato;
import br.com.vinicius.objeto.Apresentacao;
import br.com.vinicius.objeto.Avaliacao;
import br.com.vinicius.objeto.Candidato;
import br.com.vinicius.objeto.Musica;
import br.com.vinicius.objeto.Requisito;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author SATC
 */
public class JrApresentaca extends javax.swing.JFrame {
   ArrayList<Avaliacao> aval = new ArrayList<>();
    /**
     * Creates new form JrApresentaca
     */
    public JrApresentaca() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLblApresentacoes = new javax.swing.JLabel();
        jPnlMusica = new javax.swing.JPanel();
        jLblMusica = new javax.swing.JLabel();
        jLblArtista = new javax.swing.JLabel();
        jLblGenero = new javax.swing.JLabel();
        jLblTempo = new javax.swing.JLabel();
        jLblNomeMusica = new javax.swing.JLabel();
        jTFArtista = new javax.swing.JTextField();
        jTFNomeMusica = new javax.swing.JTextField();
        jTFGenero = new javax.swing.JTextField();
        jTFTempo = new javax.swing.JTextField();
        jPnlApresentacao = new javax.swing.JPanel();
        jLblApresentacao = new javax.swing.JLabel();
        jLblAltoral = new javax.swing.JLabel();
        jLblCandidato = new javax.swing.JLabel();
        jLblAdaptado1 = new javax.swing.JLabel();
        jRBAltoralSim = new javax.swing.JRadioButton();
        jRBAltoralNao = new javax.swing.JRadioButton();
        jRBAdaptadaSim = new javax.swing.JRadioButton();
        jRBAdaptadaNao = new javax.swing.JRadioButton();
        jTFCodigoCandidato = new javax.swing.JTextField();
        jBtnLista = new javax.swing.JButton();
        jBtnCadastrar = new javax.swing.JButton();
        jBtnSair = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLblRequisitos = new javax.swing.JLabel();
        jLblRequisito = new javax.swing.JLabel();
        jTFRequisito = new javax.swing.JTextField();
        jLblNota = new javax.swing.JLabel();
        jTFNota = new javax.swing.JTextField();
        jLblStatus = new javax.swing.JLabel();
        jTFStatus = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLblApresentacoes.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLblApresentacoes.setText("Apresentações");

        jPnlMusica.setBackground(new java.awt.Color(153, 0, 0));
        jPnlMusica.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 51, 51)));

        jLblMusica.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLblMusica.setText("musica");

        jLblArtista.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLblArtista.setText("Artista :");

        jLblGenero.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLblGenero.setText("Genero :");

        jLblTempo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLblTempo.setText("Tempo :");

        jLblNomeMusica.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLblNomeMusica.setText("Nome da Musica :");

        jTFArtista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFArtistaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPnlMusicaLayout = new javax.swing.GroupLayout(jPnlMusica);
        jPnlMusica.setLayout(jPnlMusicaLayout);
        jPnlMusicaLayout.setHorizontalGroup(
            jPnlMusicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlMusicaLayout.createSequentialGroup()
                .addGroup(jPnlMusicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPnlMusicaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLblArtista))
                    .addGroup(jPnlMusicaLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jLblMusica))
                    .addGroup(jPnlMusicaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPnlMusicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLblNomeMusica)
                            .addComponent(jLblGenero)
                            .addComponent(jLblTempo)))
                    .addGroup(jPnlMusicaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTFArtista, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPnlMusicaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTFNomeMusica, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPnlMusicaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTFGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPnlMusicaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTFTempo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jPnlMusicaLayout.setVerticalGroup(
            jPnlMusicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlMusicaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLblMusica)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLblArtista)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTFArtista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLblNomeMusica)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTFNomeMusica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLblGenero)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTFGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLblTempo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTFTempo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jPnlApresentacao.setBackground(new java.awt.Color(153, 0, 0));
        jPnlApresentacao.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 51, 51)));

        jLblApresentacao.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLblApresentacao.setText("Apresentação");

        jLblAltoral.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLblAltoral.setText("Altoral :");

        jLblCandidato.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLblCandidato.setText("Codigo do Candidato :");

        jLblAdaptado1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLblAdaptado1.setText("Adaptado :");

        jRBAltoralSim.setBackground(new java.awt.Color(153, 0, 0));
        jRBAltoralSim.setText("Sim");

        jRBAltoralNao.setBackground(new java.awt.Color(153, 0, 0));
        jRBAltoralNao.setText("Não");

        jRBAdaptadaSim.setBackground(new java.awt.Color(153, 0, 0));
        jRBAdaptadaSim.setText("Sim");

        jRBAdaptadaNao.setBackground(new java.awt.Color(153, 0, 0));
        jRBAdaptadaNao.setText("Não");

        jTFCodigoCandidato.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTFCodigoCandidatoMouseClicked(evt);
            }
        });
        jTFCodigoCandidato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFCodigoCandidatoActionPerformed(evt);
            }
        });

        jBtnLista.setBackground(new java.awt.Color(102, 102, 102));
        jBtnLista.setText("Lista de Candidatos");
        jBtnLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnListaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPnlApresentacaoLayout = new javax.swing.GroupLayout(jPnlApresentacao);
        jPnlApresentacao.setLayout(jPnlApresentacaoLayout);
        jPnlApresentacaoLayout.setHorizontalGroup(
            jPnlApresentacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlApresentacaoLayout.createSequentialGroup()
                .addGroup(jPnlApresentacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPnlApresentacaoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPnlApresentacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPnlApresentacaoLayout.createSequentialGroup()
                                .addComponent(jRBAdaptadaSim)
                                .addGap(18, 18, 18)
                                .addComponent(jRBAdaptadaNao))
                            .addGroup(jPnlApresentacaoLayout.createSequentialGroup()
                                .addComponent(jRBAltoralSim)
                                .addGap(18, 18, 18)
                                .addComponent(jRBAltoralNao))
                            .addComponent(jLblAltoral)
                            .addComponent(jLblCandidato)
                            .addComponent(jLblAdaptado1)
                            .addComponent(jTFCodigoCandidato, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBtnLista)))
                    .addGroup(jPnlApresentacaoLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jLblApresentacao)))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        jPnlApresentacaoLayout.setVerticalGroup(
            jPnlApresentacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlApresentacaoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLblApresentacao)
                .addGap(18, 18, 18)
                .addComponent(jLblAltoral)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPnlApresentacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRBAltoralSim)
                    .addComponent(jRBAltoralNao))
                .addGap(18, 18, 18)
                .addComponent(jLblAdaptado1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPnlApresentacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRBAdaptadaSim)
                    .addComponent(jRBAdaptadaNao))
                .addGap(31, 31, 31)
                .addComponent(jLblCandidato)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTFCodigoCandidato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtnLista)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jBtnCadastrar.setBackground(new java.awt.Color(102, 102, 102));
        jBtnCadastrar.setText("Cadastrar");
        jBtnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCadastrarActionPerformed(evt);
            }
        });

        jBtnSair.setBackground(new java.awt.Color(102, 102, 102));
        jBtnSair.setText("Sair");
        jBtnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSairActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(153, 0, 0));

        jLblRequisitos.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLblRequisitos.setText("Requisitos");

        jLblRequisito.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLblRequisito.setText("Requisito :");

        jTFRequisito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFRequisitoActionPerformed(evt);
            }
        });

        jLblNota.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLblNota.setText("Nota :");

        jTFNota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFNotaActionPerformed(evt);
            }
        });

        jLblStatus.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLblStatus.setText("Status :");

        jTFStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFStatusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLblRequisitos)
                .addGap(48, 48, 48))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLblRequisito)
                    .addComponent(jTFRequisito, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLblNota)
                    .addComponent(jTFNota, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLblStatus)
                    .addComponent(jTFStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLblRequisitos)
                .addGap(18, 18, 18)
                .addComponent(jLblRequisito)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTFRequisito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLblNota)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTFNota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLblStatus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTFStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(83, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPnlMusica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPnlApresentacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jBtnCadastrar)
                        .addGap(18, 18, 18)
                        .addComponent(jBtnSair)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLblApresentacoes)
                .addGap(251, 251, 251))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLblApresentacoes)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPnlMusica, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPnlApresentacao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnCadastrar)
                    .addComponent(jBtnSair))
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTFArtistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFArtistaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFArtistaActionPerformed

    private void jTFCodigoCandidatoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTFCodigoCandidatoMouseClicked

    }//GEN-LAST:event_jTFCodigoCandidatoMouseClicked

    private void jTFCodigoCandidatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFCodigoCandidatoActionPerformed

    }//GEN-LAST:event_jTFCodigoCandidatoActionPerformed

    private void jBtnListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnListaActionPerformed
        String list = " ";
        for (Candidato cand : SCandidato.getInstance().getCandidato()) {
            list += SCandidato.getInstance().getCandidato().indexOf(cand)+ " : "+ cand.getNome() +"\n";
        }
        JOptionPane.showMessageDialog(this, list);
    }//GEN-LAST:event_jBtnListaActionPerformed

    private void jBtnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCadastrarActionPerformed
        String artista = jTFArtista.getText();
        String nomemusica = jTFNomeMusica.getText();
        String Genero = jTFGenero.getText();
        float tempo = Float.parseFloat(jTFTempo.getText());

        Musica m = new Musica(artista, nomemusica, Genero, tempo);

        Boolean altoral = null, adaptado = null;

        if (jRBAltoralSim.isSelected()) {
            altoral = true;
        } else {
            if (jRBAltoralNao.isSelected()) {
                altoral = false;
            }

        }

        if (jRBAdaptadaSim.isSelected()) {
            adaptado = true;
        } else {
            if (jRBAdaptadaNao.isSelected()) {
                adaptado = false;
            }
        }
        int codigocandidato = Integer.parseInt(jTFCodigoCandidato.getText());

        Apresentacao a = new Apresentacao(altoral, adaptado ,SCandidato.getInstance().getCandidato().get(Integer.parseInt(jTFCodigoCandidato.getText())),m);

        String requisitos = jTFRequisito.getText();
        int nota = Integer.parseInt(jTFNota.getText());
        char status = jTFStatus.getText().charAt(0);
        
        
        
        Requisito r = new Requisito(requisitos, nota, status);
        
        for (Avaliacao avali : aval) {
            avali.getRequisitos().add(r);
        }
       
        
        
        Avaliacao ava = new Avaliacao(a, tempo);
        SAvaliacao.getInstance().getAvaliacao().add(ava);
    }//GEN-LAST:event_jBtnCadastrarActionPerformed

    private void jBtnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSairActionPerformed
        setVisible(false);
    }//GEN-LAST:event_jBtnSairActionPerformed

    private void jTFRequisitoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFRequisitoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFRequisitoActionPerformed

    private void jTFNotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFNotaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFNotaActionPerformed

    private void jTFStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFStatusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JrApresentaca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JrApresentaca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JrApresentaca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JrApresentaca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JrApresentaca().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnCadastrar;
    private javax.swing.JButton jBtnLista;
    private javax.swing.JButton jBtnSair;
    private javax.swing.JLabel jLblAdaptado1;
    private javax.swing.JLabel jLblAltoral;
    private javax.swing.JLabel jLblApresentacao;
    private javax.swing.JLabel jLblApresentacoes;
    private javax.swing.JLabel jLblArtista;
    private javax.swing.JLabel jLblCandidato;
    private javax.swing.JLabel jLblGenero;
    private javax.swing.JLabel jLblMusica;
    private javax.swing.JLabel jLblNomeMusica;
    private javax.swing.JLabel jLblNota;
    private javax.swing.JLabel jLblRequisito;
    private javax.swing.JLabel jLblRequisitos;
    private javax.swing.JLabel jLblStatus;
    private javax.swing.JLabel jLblTempo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPnlApresentacao;
    private javax.swing.JPanel jPnlMusica;
    private javax.swing.JRadioButton jRBAdaptadaNao;
    private javax.swing.JRadioButton jRBAdaptadaSim;
    private javax.swing.JRadioButton jRBAltoralNao;
    private javax.swing.JRadioButton jRBAltoralSim;
    private javax.swing.JTextField jTFArtista;
    private javax.swing.JTextField jTFCodigoCandidato;
    private javax.swing.JTextField jTFGenero;
    private javax.swing.JTextField jTFNomeMusica;
    private javax.swing.JTextField jTFNota;
    private javax.swing.JTextField jTFRequisito;
    private javax.swing.JTextField jTFStatus;
    private javax.swing.JTextField jTFTempo;
    // End of variables declaration//GEN-END:variables
}
