/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.vinicius;

import Singleton.SApresentacao;
import Singleton.SCandidato;
import Singleton.SJurado;
import Singleton.SRequisito;
import javax.swing.JOptionPane;

/**
 *
 * @author SATC
 */
public class JRConsuta extends javax.swing.JFrame {

    /**
     * Creates new form JRConsuta
     */
    public JRConsuta() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLblConsuta = new javax.swing.JLabel();
        jBtnCandidato = new javax.swing.JButton();
        jBtnJurado = new javax.swing.JButton();
        jBtnApresentacao = new javax.swing.JButton();
        jBtnRequisitos = new javax.swing.JButton();
        jBtnSair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLblConsuta.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLblConsuta.setText("consutar");

        jBtnCandidato.setBackground(new java.awt.Color(102, 102, 102));
        jBtnCandidato.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jBtnCandidato.setText("Candidato");
        jBtnCandidato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCandidatoActionPerformed(evt);
            }
        });

        jBtnJurado.setBackground(new java.awt.Color(102, 102, 102));
        jBtnJurado.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jBtnJurado.setText("Jurado");
        jBtnJurado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnJuradoActionPerformed(evt);
            }
        });

        jBtnApresentacao.setBackground(new java.awt.Color(102, 102, 102));
        jBtnApresentacao.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jBtnApresentacao.setText("Apresentacao");
        jBtnApresentacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnApresentacaoActionPerformed(evt);
            }
        });

        jBtnRequisitos.setBackground(new java.awt.Color(102, 102, 102));
        jBtnRequisitos.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jBtnRequisitos.setText("Requisitos");
        jBtnRequisitos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnRequisitosActionPerformed(evt);
            }
        });

        jBtnSair.setBackground(new java.awt.Color(102, 102, 102));
        jBtnSair.setText("Sair");
        jBtnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBtnCandidato)
                            .addComponent(jBtnJurado)
                            .addComponent(jBtnApresentacao)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBtnRequisitos)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                                .addComponent(jBtnSair))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(jLblConsuta)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLblConsuta)
                .addGap(37, 37, 37)
                .addComponent(jBtnCandidato)
                .addGap(18, 18, 18)
                .addComponent(jBtnJurado)
                .addGap(18, 18, 18)
                .addComponent(jBtnApresentacao)
                .addGap(18, 18, 18)
                .addComponent(jBtnRequisitos)
                .addContainerGap(32, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBtnSair)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnCandidatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCandidatoActionPerformed
      JOptionPane.showMessageDialog(this, SCandidato.getInstance().toString());
    }//GEN-LAST:event_jBtnCandidatoActionPerformed

    private void jBtnJuradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnJuradoActionPerformed
        JOptionPane.showMessageDialog(this, SJurado.getInstance().toString());
    }//GEN-LAST:event_jBtnJuradoActionPerformed

    private void jBtnApresentacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnApresentacaoActionPerformed
        JOptionPane.showMessageDialog(this, SApresentacao.getInstance().toString());
    }//GEN-LAST:event_jBtnApresentacaoActionPerformed

    private void jBtnRequisitosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnRequisitosActionPerformed
        JOptionPane.showMessageDialog(this, SRequisito.getInstance().toString()); 
    }//GEN-LAST:event_jBtnRequisitosActionPerformed

    private void jBtnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSairActionPerformed
        setVisible(false);
    }//GEN-LAST:event_jBtnSairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JRConsuta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JRConsuta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JRConsuta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JRConsuta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JRConsuta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnApresentacao;
    private javax.swing.JButton jBtnCandidato;
    private javax.swing.JButton jBtnJurado;
    private javax.swing.JButton jBtnRequisitos;
    private javax.swing.JButton jBtnSair;
    private javax.swing.JLabel jLblConsuta;
    // End of variables declaration//GEN-END:variables
}
